name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Run Ruff, Ty, and TOML checks
        run: |
          uv run --with ruff --with ty --with tombi ruff format --check
          uv run --with ruff --with ty --with tombi ruff check
          uv run --with ruff --with ty --with tombi ty check
          uv run --with ruff --with ty --with tombi tombi lint pyproject.toml
